### ISSUE TITLE
伪代码块无法正常渲染

### ISSUE THREAD

**Issue by simolark** [Tang1705/BJTU-Bachelor-Thesis#1]
如题，尝试渲染伪代码块的时候会出现异常，无法正常渲染，会出现格式混乱，异常空格等情况，且相同的语句在简单环境下可以正常渲染

**Comment by Tang1705** [comment]
感谢你提出的问题。由于你没有提供相关报错信息，我无法复现和定位相关问题，以下是一些解决办法。

1. 使用 TexLive 或 MacTex，并使用 XeLaTex 编译，而不要使用 CTex；

2. 在代码库中提供了example 和 sample 两个文件夹，均提供了伪代码的编写示例，请参考是否可以满足需求。

**Comment by Tang1705** [comment]
algorithmic 包与文件中多个包存在冲突，如需使用，在 bjtu-bachelor-thesis.cls 文件中，将 \RequirePackage[linesnumbered,ruled,vlined]{algorithm2e} 一行注视，添加 如下两行，可解决问题。

\RequirePackage{algorithm}
\RequirePackage{algorithmicx}
